version: '3'

services:
  webserver:
    image: 7206075514/acmgo:latest
    ports: 
      - "80:8080"
    worker:
      deploy:
        mode: replicated
      replicas: 6
      placement:
        max_replicas_per_node: 1 
