version: '3'

services:
  webserver:
    image: 7206075514/acmgo:latest
    ports: 
      - "80:8080"
    deploy:
      mode: replicated
      replicas: 3
      restart_porlicy:
        condition: on-failure
    